name: Kurtosis Devnet

on:
  push:
    branches: [eigenda-develop]
  pull_request:

env:
  KURTOSIS_VERSION: 'latest'

jobs:
  # This is an optimism devnet which talks to the eigenda holesky testnet via an eigenda-proxy.
  # TODO: we should connect this to an eigenda kurtosis devnet instead of using our holesky testnet.
  run_op_eigenda_holesky_devnet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Kurtosis
        uses: ./.github/actions/kurtosis-install
        with:
          version: ${{ env.KURTOSIS_VERSION }}
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - uses: extractions/setup-just@v2
      # Needed by the just eigenda-holesky-devnet command below
      # These secrets get injected into the eigenda-holesky.yaml kurtosis config file
      - name: Create EigenDA secrets file
        run: |
          cat > kurtosis-devnet/eigenda-secrets.json << EOF
          {
            "secrets": {
              "eigenda.signer-private-key-hex": "${{ secrets.EIGENDA_V1_HOLESKY_TESTNET_SIGNER_KEY }}",
              "eigenda.eth_rpc": "https://ethereum-holesky-rpc.publicnode.com"
            }
          }
          EOF
      - name: Run Starlark
        working-directory: kurtosis-devnet
        run: |
          just eigenda-holesky-devnet
